// language: C#, file: Services/ExportService.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

public static class ExportService
{
    // ═══════════════════════════════════════════════════════════
    //   TXT — універсальний формат
    // ═══════════════════════════════════════════════════════════

    public static string RenderTxt(LabelCollection col)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# RustOffsets.txt — generated by IL2CppToolkit");
        sb.AppendLine($"# game: {col.GameId}");
        sb.AppendLine($"# generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("# ═══ FORMAT ═══");
        sb.AppendLine("# instance:  Class.semantic = 0xOFFSET         (instance field)");
        sb.AppendLine("# chain:     Class.semantic = chain(0xRVA, 0xB8, 0xSLOT)");
        sb.AppendLine("#   chain resolve:  module + RVA → ptr → read(+0xB8) → read(+SLOT)");
        sb.AppendLine();

        var instances = col.Labels.Where(x => !x.IsChain).OrderBy(x => x.Class).ThenBy(x => x.Semantic).ToList();
        var chains = col.Labels.Where(x => x.IsChain).OrderBy(x => x.Class).ThenBy(x => x.Semantic).ToList();

        sb.AppendLine("[instance]");
        foreach (var l in instances)
            sb.AppendLine($"{l.Class}.{l.Semantic,-24} = 0x{l.Offset:X}");

        if (chains.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("[chain]");
            foreach (var l in chains)
            {
                var parts = new List<string> { $"0x{l.ClassRva:X}" };
                parts.AddRange(l.Chain.Select(x => $"0x{x:X}"));
                sb.AppendLine($"{l.Class}.{l.Semantic,-24} = chain({string.Join(", ", parts)})");
            }
        }

        return sb.ToString();
    }

    // ═══════════════════════════════════════════════════════════
    //   C++ header
    // ═══════════════════════════════════════════════════════════

    public static string RenderCppHeader(LabelCollection col)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// offsets.hpp — generated by IL2CppToolkit");
        sb.AppendLine($"// game: {col.GameId}   {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("#pragma once");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine();
        sb.AppendLine("namespace offsets {");
        sb.AppendLine("    // ═══ instance fields ═══");
        sb.AppendLine("    namespace instance {");
        foreach (var grp in col.Labels.Where(x => !x.IsChain).GroupBy(x => x.Class).OrderBy(x => x.Key))
        {
            sb.AppendLine($"        namespace {Sanitize(grp.Key)} {{");
            foreach (var l in grp.OrderBy(x => x.Semantic))
                sb.AppendLine($"            constexpr uintptr_t {Sanitize(l.Semantic)} = 0x{l.Offset:X}; // {l.Type}");
            sb.AppendLine("        }");
        }
        sb.AppendLine("    }");

        var chains = col.Labels.Where(x => x.IsChain).ToList();
        if (chains.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    // ═══ chains (static via Il2CppClass) ═══");
            sb.AppendLine("    // resolve:  auto klass = RPM(module + class_rva);");
            sb.AppendLine("    //           auto sf   = RPM(klass + 0xB8);");
            sb.AppendLine("    //           auto val  = RPM(sf + slot_offset);");
            sb.AppendLine("    namespace chains {");
            foreach (var grp in chains.GroupBy(x => x.Class).OrderBy(x => x.Key))
            {
                sb.AppendLine($"        namespace {Sanitize(grp.Key)} {{");
                foreach (var l in grp.OrderBy(x => x.Semantic))
                {
                    string sn = Sanitize(l.Semantic);
                    sb.AppendLine($"            constexpr uintptr_t {sn}_rva  = 0x{l.ClassRva:X};");
                    sb.AppendLine($"            constexpr int       {sn}_sf   = 0x{l.Chain[0]:X};");
                    if (l.Chain.Count > 1)
                        sb.AppendLine($"            constexpr int       {sn}_off  = 0x{l.Chain[1]:X};");
                }
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ═══════════════════════════════════════════════════════════
    //   C# class
    // ═══════════════════════════════════════════════════════════

    public static string RenderCsClass(LabelCollection col)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Offsets.cs — generated by IL2CppToolkit");
        sb.AppendLine($"// game: {col.GameId}   {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("public static class Offsets");
        sb.AppendLine("{");

        foreach (var grp in col.Labels.Where(x => !x.IsChain).GroupBy(x => x.Class).OrderBy(x => x.Key))
        {
            sb.AppendLine($"    // {grp.Key}  (instance)");
            foreach (var l in grp.OrderBy(x => x.Semantic))
                sb.AppendLine($"    public const int {Sanitize(l.Semantic)} = 0x{l.Offset:X};");
            sb.AppendLine();
        }

        var chains = col.Labels.Where(x => x.IsChain).ToList();
        if (chains.Count > 0)
        {
            sb.AppendLine("    // ═══ chains ═══");
            foreach (var grp in chains.GroupBy(x => x.Class).OrderBy(x => x.Key))
            {
                sb.AppendLine($"    // {grp.Key}");
                foreach (var l in grp.OrderBy(x => x.Semantic))
                {
                    string sn = Sanitize(l.Semantic);
                    sb.AppendLine($"    public const long {sn}_rva  = 0x{l.ClassRva:X};");
                    sb.AppendLine($"    public const int  {sn}_sf   = 0x{l.Chain[0]:X};");
                    if (l.Chain.Count > 1)
                        sb.AppendLine($"    public const int  {sn}_off  = 0x{l.Chain[1]:X};");
                }
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string RenderJson(LabelCollection col) => JsonStore.Serialize(col);

    static string Sanitize(string s)
    {
        if (string.IsNullOrEmpty(s)) return "x";
        var sb = new StringBuilder();
        foreach (char c in s)
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        if (char.IsDigit(sb[0])) sb.Insert(0, '_');
        return sb.ToString();
    }
}